"""add device registrations

Revision ID: ded5c63addd2
Revises: 92999bdb4769
Create Date: 2026-03-24 16:42:10.722178

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'ded5c63addd2'
down_revision: Union[str, None] = '92999bdb4769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_registrations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('kc_user_id', sa.String(length=36), nullable=True),
    sa.Column('fingerprint_hash', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_id', name='uq_device_user')
    )
    op.create_index(op.f('ix_device_registrations_device_id'), 'device_registrations', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_registrations_user_id'), 'device_registrations', ['user_id'], unique=False)
    op.add_column('sessions', sa.Column('device_id', sa.String(length=36), nullable=True))
    op.add_column('sessions', sa.Column('kc_user_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_sessions_device_id'), 'sessions', ['device_id'], unique=False)
    op.create_unique_constraint('uq_social_provider_uid', 'social_accounts', ['provider', 'provider_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_social_provider_uid', 'social_accounts', type_='unique')
    op.drop_index(op.f('ix_sessions_device_id'), table_name='sessions')
    op.drop_column('sessions', 'kc_user_id')
    op.drop_column('sessions', 'device_id')
    op.drop_index(op.f('ix_device_registrations_user_id'), table_name='device_registrations')
    op.drop_index(op.f('ix_device_registrations_device_id'), table_name='device_registrations')
    op.drop_table('device_registrations')
    # ### end Alembic commands ###